export enum ResourceType {
    ARMOR = "ARMOR",
    BARRELS = "BARRELS",
    CLOTHES = "CLOTHES",
    FOOD = "FOOD",
    HIDE = "HIDE",
    HORSE = "HORSE",
    JEWELLERIES = "JEWELLERIES",
    METAL = "METAL",
    PARCHMENT = "PARCHMENT",
    STONE = "STONE",
    TOOLS = "TOOLS",
    WEAPONS = "WEAPONS",
    WINE = "WINE",
    WOOD = "WOOD",
}