version: 0.0
os: linux

files:
    - source: /
      destination: /home/ubuntu/server

permissions:
    - object: /
      pattern: "**"
      owner: ubuntu
      group: ubuntu


hooks:
    ApplicationStop:
      - location: kill_container.sh
        timeout: 300
    AfterInstall:
        - location: load_image.sh
          timeout: 300
    ApplicationStart:
        - location: start_container.sh
          timeout: 300