version: 0.0
os: linux

files:
    - source: /
      destination: /home/ubuntu/server

permissions:
    - object: /
      pattern: "**"
      owner: ubuntu
      group: ubuntu


hooks:
    ApplicationStop:
      - location: infrastructure/aws/backend/stop.sh
        timeout: 300
    AfterInstall:
        - location: infrastructure/aws/backend/prepare.sh
          timeout: 300
    ApplicationStart:
        - location: infrastructure/aws/backend/start.sh
          timeout: 300