FROM eclipse-temurin:17

COPY --chown=gradle:gradle . /home/gradle/build

WORKDIR /home/gradle/build

RUN ./gradlew --version

RUN ./gradlew dependencies \
	strategy-game-app:dependencies \
	strategy-game-common-arangodb:dependencies \
	strategy-game-common-data:dependencies \
	strategy-game-ecosim:dependencies \
	strategy-game-engine:dependencies \
	strategy-game-gateway:dependencies \
	strategy-game-pathfinding:dependencies \
	strategy-game-playerpov:dependencies \
	strategy-game-users:dependencies \
	strategy-game-worldgen:dependencies \
	strategy-game-worlds:dependencies

RUN rm -rf /home/gradle