kotlin.code.style=official

# project id
projectGroupId=io.github.smiley4
projectVersion=0.7.0

# dependency versions
versionArangoDb=7.12.0
versionArrow=2.0.0-alpha.4
versionAwsSdk=1.12.777
versionJacksonDataformatVelocypack=4.4.0
versionJanino=3.1.12
versionKoin=4.1.0-Beta1
versionKoson=1.2.9
versionKotest=6.0.0.M1
versionKotestExtensionKtor=1.0.3
versionKotestExtensionTestContainers=2.0.2
versionKotlinLogging=4.0.0-beta-2
versionKotlinTest=1.5.31
versionKtor=3.0.2
versionKtorSwaggerUi=4.1.1
versionLogback=1.5.12
versionLogstashLogbackEncoder=8.0
versionMicrometerPrometheus=1.13.6
versionMockk=1.13.13
versionSlf4jCoroutines=1.9.0
versionJacksonModuleKotlin=2.18.1
versionKotlinxCoroutines=1.9.0
versionTypesafeConfig=1.4.3