apiVersion: apps/v1
kind: Deployment
metadata:
    name: elasticsearch
    namespace: strategy-game
    labels:
        name: elasticsearch
spec:
    selector:
        matchLabels:
            name: elasticsearch
    template:
        metadata:
            labels:
                name: elasticsearch
        spec:
            containers:
                -   name: elasticsearch
                    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
                    env:
                        -   name: discovery.type
                            value: single-node
                    ports:
                        -   containerPort: 9200
                            name: http
                            protocol: TCP
                    resources:
                        limits:
                            cpu: 500m
                            memory: 4Gi
                        requests:
                            cpu: 500m
                            memory: 4Gi


---


apiVersion: v1
kind: Service
metadata:
    name: elasticsearch
    namespace: strategy-game
    labels:
        name: elasticsearch
spec:
    selector:
        name: elasticsearch
    ports:
        -   name: "9200"
            port: 9200
            targetPort: 9200
