---
apiVersion: v1
kind: ConfigMap
metadata:
    name: filebeat-config
    namespace: strategy-game
    labels:
        k8s-app: filebeat
data:
    filebeat.yml: |-
        
        filebeat.autodiscover:
            providers:
                - type: kubernetes
                  node: ${NODE_NAME}
                  hints.enabled: true
                  hints.default_config:
                      type: container
                      paths:
                          - /var/log/containers/*${data.kubernetes.container.id}.log
        
        processors:
            - add_cloud_metadata: null
            - add_host_metadata: null
            - decode_json_fields:
                  fields:
                      - message
                  process_array: false
                  max_depth: 3
                  target: ""
                  overwrite_keys: true
                  add_error_key: true
        
        output.elasticsearch:
            hosts:
                - ${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}


---


apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: filebeat
    namespace: strategy-game
    labels:
        k8s-app: filebeat
spec:
    selector:
        matchLabels:
            k8s-app: filebeat
    template:
        metadata:
            labels:
                k8s-app: filebeat
        spec:
            serviceAccountName: filebeat
            terminationGracePeriodSeconds: 30
            hostNetwork: true
            dnsPolicy: ClusterFirstWithHostNet
            containers:
                - name: filebeat
                  image: docker.elastic.co/beats/filebeat:7.9.3
                  args: [
                      "-c", "/etc/filebeat.yml",
                      "-e",
                  ]
                  env:
                      - name: ELASTICSEARCH_HOST
                        value: elasticsearch
                      - name: ELASTICSEARCH_PORT
                        value: "9200"
                      - name: ELASTIC_CLOUD_ID
                        value:
                      - name: ELASTIC_CLOUD_AUTH
                        value:
                      - name: NODE_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: spec.nodeName
                  securityContext:
                      runAsUser: 0
                  resources:
                      limits:
                          memory: 200Mi
                      requests:
                          cpu: 100m
                          memory: 100Mi
                  volumeMounts:
                      - name: config
                        mountPath: /etc/filebeat.yml
                        readOnly: true
                        subPath: filebeat.yml
                      - name: data
                        mountPath: /usr/share/filebeat/data
                      - name: varlibdockercontainers
                        mountPath: /var/lib/docker/containers
                        readOnly: true
                      - name: varlog
                        mountPath: /var/log
                        readOnly: true
            volumes:
                - name: config
                  configMap:
                      defaultMode: 0640
                      name: filebeat-config
                - name: varlibdockercontainers
                  hostPath:
                      path: /var/lib/docker/containers
                - name: varlog
                  hostPath:
                      path: /var/log
                - name: data
                  hostPath:
                      path: /var/lib/filebeat-data
                      type: DirectoryOrCreate


---


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: filebeat
subjects:
    - kind: ServiceAccount
      name: filebeat
      namespace: strategy-game
roleRef:
    kind: ClusterRole
    name: filebeat
    apiGroup: rbac.authorization.k8s.io


---


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: filebeat
    labels:
        k8s-app: filebeat
rules:
    - apiGroups: [""] # "" indicates the core API group
      resources:
          - namespaces
          - pods
      verbs:
          - get
          - watch
          - list

---


apiVersion: v1
kind: ServiceAccount
metadata:
    name: filebeat
    namespace: strategy-game
    labels:
        k8s-app: filebeat
---
