apiVersion: apps/v1
kind: Deployment
metadata:
    name: kibana
    namespace: strategy-game
    labels:
        name: kibana
spec:
    selector:
        matchLabels:
            name: kibana
    template:
        metadata:
            labels:
                name: kibana
        spec:
            containers:
                -   name: kibana
                    image: docker.elastic.co/kibana/kibana:7.4.1
                    env:
                        -   name: ELASTICSEARCH_URL
                            value: http://elasticsearch:9200
                        -   name: XPACK_SECURITY_ENABLED
                            value: "true"
                    ports:
                        -   containerPort: 5601
                            name: http
                            protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
    name: kibana
    namespace: strategy-game
    labels:
        service: kibana
spec:
    type: NodePort
    selector:
        name: kibana
    ports:
        -   port: 5601
            targetPort: 5601