pipeline {
	agent any
	stages {
		stage("Docker Build") {
			steps {
				dir("strategy-game-backend") {
					script {
						sh "docker build --platform linux/amd64 -t 627717213620.dkr.ecr.eu-central-1.amazonaws.com/strategy-game:latest ."
					}
				}
			}
		}
		stage("Docker Push") {
			steps {
				script {
					sh "docker tag 627717213620.dkr.ecr.eu-central-1.amazonaws.com/strategy-game:latest 627717213620.dkr.ecr.eu-central-1.amazonaws.com/strategy-game:${env.GIT_COMMIT.take(7)}"
					sh "docker push 627717213620.dkr.ecr.eu-central-1.amazonaws.com/strategy-game:latest"
					sh "docker push 627717213620.dkr.ecr.eu-central-1.amazonaws.com/strategy-game:${env.GIT_COMMIT.take(7)}"
				}
			}
		}
		stage("Docker Cleanup") {
			steps {
				script {
					sh "docker rm -vf \$(docker ps -aq)"
					sh "docker rmi -f \$(docker images -aq)"
				}
			}
		}
	}
}