package io.github.smiley4.strategygame.backend.commondata

enum class ResourceLedgerDetailType {

    UNKNOWN_CONSUMPTION,
    UNKNOWN_PRODUCTION,
    UNKNOWN_MISSING,

    BUILDING_CONSUMPTION,
    BUILDING_PRODUCTION,
    BUILDING_MISSING,

    POPULATION_BASE_CONSUMPTION,
    POPULATION_BASE_MISSING,

    POPULATION_GROWTH_CONSUMPTION,
    POPULATION_GROWTH_MISSING,

    PRODUCTION_QUEUE_CONSUMPTION,
    PRODUCTION_QUEUE_MISSING,
    PRODUCTION_QUEUE_REFUND,

    SHARED_GIVE,
    SHARED_TAKE

}