[versions]

# Language & Build
kotlin = "2.2.21"
jvm-compile = "21"
jvm-target = "11"

# Plugins
shadow = "8.1.1"
detekt = "1.23.8"
dependencycheck = "12.2.0"
versions-plugin = "0.53.0"

# Libraries
arangodb = "7.15.0"
arangodb-jackson-dataformat-velocypack = "4.5.0"
arrow = "2.0.0-alpha.4"
aws-sdk = "1.12.777"
dotlin = "1.0.2"
hdr-histogram = "2.1.12"
jackson-kotlin = "2.18.1"
janino = "3.1.12"
koin = "4.1.0-Beta1"
koson = "1.2.9"
kotest = "6.0.0.M1"
kotest-testcontainers = "2.0.2"
kotlin-logging = "4.0.0-beta-2"
kotlinx-coroutines = "1.9.0"
ktor = "3.0.2"
ktor-swagger-ui = "4.1.1"
logback = "1.5.12"
logstash-logback-encoder = "8.0"
micrometer-prometheus = "1.13.6"
mockk = "1.13.13"
slf4j-coroutines = "1.9.0"
typesafe-config = "1.4.3"



[libraries]

# Ktor
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-authjwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-calllogging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-contentnegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-core-jvm = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-htmlbuilder = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }
ktor-server-metrics = { module = "io.ktor:ktor-server-metrics", version.ref = "ktor" }
ktor-server-metrics-micrometer = { module = "io.ktor:ktor-server-metrics-micrometer", version.ref = "ktor" }
ktor-server-netty-jvm = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }
ktor-server-statuspages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-swagger-ui =  { module = "io.github.smiley4:ktor-swagger-ui", version.ref = "ktor-swagger-ui"}

# Logging
janino = { module = "org.codehaus.janino:janino", version.ref = "janino" }
kotlin-logging-jvm = { module = "io.github.microutils:kotlin-logging-jvm", version.ref = "kotlin-logging" }
kotlinx-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "slf4j-coroutines" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash-logback-encoder" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-ktor3 = { module = "io.insert-koin:koin-ktor3", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5", version.ref = "koin" }

# ArangoDB
arangodb-java-driver = { module = "com.arangodb:arangodb-java-driver", version.ref = "arangodb" }
arangodb-jackson-dataformat-velocypack = { module = "com.arangodb:jackson-dataformat-velocypack", version.ref = "arangodb-jackson-dataformat-velocypack" }

# Misc
dotlin = { module = "io.github.rchowell:dotlin", version.ref = "dotlin"}
hdr-histogram = { module = "org.hdrhistogram:HdrHistogram", version.ref = "hdr-histogram" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-kotlin" }
koson = { module = "com.lectra:koson", version.ref = "koson" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer-prometheus" }
typesafe-config = { module = "com.typesafe:config", version.ref = "typesafe-config" }

# AWS
aws-sdk = { module = "com.amazonaws:aws-java-sdk", version.ref = "aws-sdk"}
aws-sdk-core = { module = "com.amazonaws:aws-java-sdk-core", version.ref = "aws-sdk"}
aws-sdk-cognitoidp = { module = "com.amazonaws:aws-java-sdk-cognitoidp", version.ref = "aws-sdk"}

# Arrow
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
arrow-fx-stm = { module = "io.arrow-kt:arrow-fx-stm", version.ref = "arrow" }

# Test
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-extensions-testcontainers = { module = "io.kotest.extensions:kotest-extensions-testcontainers", version.ref = "kotest-testcontainers" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }



[plugins]

# Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Code Quality & Documentation
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependencycheck" }

# Building
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

# Utilities
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }