package io.github.smiley4.strategygame.backend.worldgen.application

import io.github.smiley4.strategygame.backend.worldgen.lib.NameGenerator

internal class NameGeneratorImpl : NameGenerator {

    companion object {

        // names copied from
        // https://www.fantasynamegenerators.com/fantasy-town-names.php
        private val SETTLEMENT_NAMES = setOf(
            "Amberdenn",
            "Arrowwind",
            "Beachside",
            "Bearfort",
            "Bonehelm",
            "Bonemore",
            "Boneshell",
            "Boulderhollow",
            "Brinestar",
            "Bronzeview",
            "Caveshire",
            "Chillland",
            "Clearburgh",
            "Clearfield",
            "Clifffall",
            "Cloudwich",
            "Coldview",
            "Darkacre",
            "Deertown",
            "Dewhorn",
            "Dewwater",
            "Dimpoint",
            "Dryfrost",
            "Dryrest",
            "Drysummit",
            "Duskdrift",
            "Duskmount",
            "Duskwater",
            "Earthfair",
            "Earthmoor",
            "Eaststrand",
            "Ebonwatch",
            "Eldershore",
            "Emberstall",
            "Everhold",
            "Fairshear",
            "Fallhelm",
            "Faygulch",
            "Fearfalls",
            "Flathallow",
            "Flatmere",
            "Frosthaven",
            "Gloomwick",
            "Goldacre",
            "Goldforest",
            "Goldfort",
            "Greenkeep",
            "Grimehand",
            "Grimeport",
            "Hazelbreach",
            "Heartpond",
            "Heartstar",
            "Highwall",
            "Icelight",
            "Kilwharf",
            "Lagoonmore",
            "Lastcairn",
            "Limestar",
            "Lostmeadow",
            "Midgrove",
            "Moonwell",
            "Mosswatch",
            "Mudgulch",
            "Mudward",
            "Muteview",
            "Neverforest",
            "Newpass",
            "Nightshield",
            "Nightvalley",
            "Oceanbarrow",
            "Oceanfield",
            "Oldpass",
            "Oldwind",
            "Quickborn",
            "Ravenhaven",
            "Redbarrow",
            "Roguebell",
            "Shadegarde",
            "Shadevale",
            "Shimmervein",
            "Shroudshore",
            "Sleetgarde",
            "Sleetshield",
            "Snakecoast",
            "Snakemoor",
            "Southhelm",
            "Starhall",
            "Starwallow",
            "Steamford",
            "Steephallow",
            "Steephost",
            "Steeprock",
            "Stillvein",
            "Stonebreak",
            "Sungulf",
            "Swanmond",
            "Timberhand",
            "Tradebarrow",
            "Whiteharbor",
            "Windgulch",
        )

        // names copied from
        // https://www.fantasynamegenerators.com/country-names.php
        private val REALM_NAMES = setOf(
            "Lewhoastein",
            "Geglaijan",
            "Vebrad",
            "Satrium",
            "Pluburg",
            "Druece",
            "Oswar",
            "Ogrua",
            "Croag Shar",
            "Truit Flana",
            "Wufriuburg",
            "Raskiavania",
            "Askon",
            "Buspye",
            "Spiacor",
            "Fruynia",
            "Uwhesh",
            "Ugrines",
            "Stuo Blos",
            "Skeyk Clait",
            "Raclaygua",
            "Qestuybar",
            "Jufla",
            "Ruscor",
            "Dreatan",
            "Pliyca",
            "Uplil",
            "Rprait",
            "Glayg Chein",
            "Swauq Thon",
            "Reswuaso",
            "Jescoirus",
            "Wutral",
            "Joshye",
            "Snuynia",
            "Bludal",
            "Eskaria",
            "Ublea",
            "Fluz Swil",
            "Bruik Snen",
            "Ruscioce",
            "Bobreura",
            "Nothil",
            "Busmana",
            "Cluador",
            "Truwana",
            "Astrain",
            "Uskor",
            "Troe Clain",
            "Scouw Blad",
        )

    }

    override fun generateSettlementName(): String {
        return SETTLEMENT_NAMES.random()
    }

    override fun generateRealmName(): String {
        return REALM_NAMES.random()
    }

}