{
 "title": "ArangoDB",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "{appname=\"arango\"}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "arangodb_server_statistics_server_uptime_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "description": "Total number of AQL queries finished.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(arangodb_aql_all_query_total[$__rate_interval])",
     "legendFormat": "Amount Queries"
    }
   ]
  },
  {
   "title": "Received & Sent Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(arangodb_client_connection_statistics_bytes_received_sum[$__rate_interval]) / rate(arangodb_client_connection_statistics_bytes_received_count[$__rate_interval])",
     "legendFormat": "Received"
    },
    {
     "expr": "increase(arangodb_client_connection_statistics_bytes_sent_sum[$__rate_interval]) / rate(arangodb_client_connection_statistics_bytes_sent_count[$__rate_interval])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Collection Sizes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "db_collection_size", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Query Memory Usage",
   "type": "timeseries",
   "description": "Total memory limit for all AQL queries combined; Total memory usage of all AQL queries currently executing. The granularity of this metric is steps of 32768 bytes",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "arangodb_aql_global_memory_usage",
     "legendFormat": "Usage"
    },
    {
     "expr": "arangodb_aql_global_memory_limit",
     "legendFormat": "Limit"
    }
   ]
  }
 ]
}