{
 "title": "Backend",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"backend\"}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "{appname=\"backend\"} != `/api/metrics`"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"backend\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "description": "The amount of used memory; The amount of memory in bytes that is committed for the Java virtual machine to use; The maximum amount of memory in bytes that can be used for memory management; ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"backend\", area=\"heap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"backend\", area=\"heap\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"backend\" ,area=\"heap\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "description": "The current number of live threads including both daemon and non-daemon threads",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"backend\"}",
     "legendFormat": "Live Threads"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "description": "The \"recent cpu usage\" of the system the application is running in",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(system_cpu_usage{job=\"backend\"}[$__rate_interval])*100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "description": "The \"recent cpu usage\" for the Java Virtual Machine process",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_usage{job=\"backend\"}[$__rate_interval])*100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Top 10 APIs",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(9, sort_desc(sum by(route, method) (ktor_http_server_requests_seconds_count{route!=\"/api/metrics\",route!=\"/api/health\"})))",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  },
  {
   "title": "Errors by API",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum by(route, method, status) (ktor_http_server_requests_seconds_count{status!=\"200\"})))",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  }
 ]
}