{
 "title": "Caddy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"caddy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "{appname=\"caddy\"}"
    }
   ]
  },
  {
   "title": "Requests over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_requests_total{job=\"caddy\"}[$__rate_interval]))",
     "legendFormat": "total requests"
    }
   ]
  },
  {
   "title": "HTTP status codes over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (code) (increase(caddy_http_request_duration_seconds_count{job=\"caddy\"}[$__rate_interval]))",
     "legendFormat": "HTTP Status {{code}}"
    }
   ]
  },
  {
   "title": "Average Request Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(caddy_http_response_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Request and Response Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(caddy_http_response_size_bytes_bucket[$__rate_interval])))",
     "legendFormat": "Response"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(caddy_http_request_size_bytes_bucket[$__rate_interval])))",
     "legendFormat": "Request"
    }
   ]
  }
 ]
}