{
 "title": "Overview",
 "time": { "from": "2022-10-23T22:55:39.308Z", "to": "2022-10-23T23:00:43.057Z" },
 "templating": {
  "list": [
   { "name": "rateInterval", "query": "1m,3m" }
  ]
 },
 "panels": [
  { "title": "Backend Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"backend\"})"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "description": "The \"recent cpu usage\" of the system the application is running in",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(system_cpu_usage{job=\"backend\"}[$rateInterval])*100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "description": "The \"recent cpu usage\" for the Java Virtual Machine process",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_usage{job=\"backend\"}[$rateInterval])*100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "description": "The amount of used memory; The amount of memory in bytes that is committed for the Java virtual machine to use; The maximum amount of memory in bytes that can be used for memory management; ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"backend\", area=\"heap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"backend\", area=\"heap\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"backend\", area=\"heap\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "description": "The current number of live threads including both daemon and non-daemon threads",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"backend\"}",
     "legendFormat": "Live Threads"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Application Action Count",
   "type": "timeseries",
   "description": "The number of core-actions - from the point of view of the backend-application.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(core_action_seconds_count[$rateInterval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Application Action Times",
   "type": "timeseries",
   "description": "The time it takes for core-actions to complete - from the point of view of the backend-application.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(core_action_seconds_sum[$rateInterval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Application Query Count",
   "type": "timeseries",
   "description": "The number of query-actions - from the point of view of the backend-application.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(db_query_seconds_count[$rateInterval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Application Query Times",
   "type": "timeseries",
   "description": "The time it takes for queries to complete - from the point of view of the backend-application.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(db_query_seconds_sum[$rateInterval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{route!=\"/api/metrics\",route!=\"/api/health\"}[$rateInterval]))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^2..$\", route!=\"/api/metrics\",route!=\"/api/health\"}[1m]))",
     "legendFormat": "2XX Success Rate"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^5..$\", route!=\"/api/metrics\",route!=\"/api/health\"}[1m]))",
     "legendFormat": "5XX Errors Rate"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^4..$\", status!=\"^401$\", route!=\"/api/metrics\",route!=\"/api/health\"}[1m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^401$\", route!=\"/api/metrics\",route!=\"/api/health\"}[1m]))",
     "legendFormat": "Unauthorized Errors Rate"
    }
   ]
  },
  {
   "title": "Top 10 APIs",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(9, sort_desc(sum by(route, method) (ktor_http_server_requests_seconds_count{route!=\"/api/metrics\",route!=\"/api/health\"})))",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  },
  {
   "title": "Errors by API",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum by(route, method, status) (ktor_http_server_requests_seconds_count{ status!=\"200\"})))",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(ktor_http_server_requests_seconds{route!=\"/api/metrics\", route!=\"/api/health\"}[$rateInterval]))",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Response time of 50% of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(ktor_http_server_requests_seconds{instance=\"$instance\", route!=\"/api/metrics\", route!=\"/api/health\", quantile=\"0.5\"}[$rateInterval])",
     "legendFormat": "{{route}} 50%"
    }
   ]
  },
  {
   "title": "Response time of 90% of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(ktor_http_server_requests_seconds{instance=\"$instance\", route!=\"/api/metrics\", route!=\"/api/health\", quantile=\"0.9\"}[$rateInterval])",
     "legendFormat": "{{route}} 95%"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"database\"})"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "arangodb_server_statistics_server_uptime_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "description": "Total number of AQL queries finished.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(arangodb_aql_all_query_total[$rateInterval])",
     "legendFormat": "Amount Queries"
    }
   ]
  },
  {
   "title": "Collection Siztes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "db_collection_size", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Query Memory Usage",
   "type": "timeseries",
   "description": "Total memory limit for all AQL queries combined; Total memory usage of all AQL queries currently executing. The granularity of this metric is steps of 32768 bytes",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "arangodb_aql_global_memory_usage",
     "legendFormat": "Query Memory Usage"
    },
    {
     "expr": "arangodb_aql_global_memory_limit",
     "legendFormat": "Query Memory Limit"
    }
   ]
  }
 ]
}