version: "3.9"

services:

    traefik:
        image: "traefik:v2.9"
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8081:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"

    app:
        image: 627717213620.dkr.ecr.eu-central-1.amazonaws.com/strategy-game:latest
        secrets:
            - awsSecretAccessKey
            - adminPassword
        environment:
            LOG_AS_JSON: "true"
        links:
            - database
        ports:
            - "8080:8080"
        entrypoint: [ '/bin/sh', '-c', 'export AWS_SECRET_ACCESS_KEY=$$(cat /var/run/secrets/awsSecretAccessKey); export ADMIN_PASSWORD=$$(cat /var/run/secrets/adminPassword); source /entrypoint.sh' ]
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: any
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.app.rule=PathPrefix(`/app`)"

    database:
        image: arangodb:3.10.0
        environment:
            ARANGO_NO_AUTH: 1
        ports:
            - "8529:8529"
        volumes:
            - arangodb_data_container:/var/lib/arangodb3
            - arangodb_apps_data_container:/var/lib/arangodb3-apps

volumes:
    arangodb_data_container:
    arangodb_apps_data_container:

secrets:
    awsSecretAccessKey:
        external: true
    adminPassword:
        external: true