version: "3.9"

services:

    reverse_proxy:
        image: "caddy:2.6.4"
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        networks:
            - "proxy-public"
        volumes:
            - "/Caddyfile:/etc/caddy/Caddyfile"
            - "caddy_data:/data"
            - "caddy_config:/config"
        deploy:
            placement:
                constraints:
                    - node.role == manager

    app:
        image: 627717213620.dkr.ecr.eu-central-1.amazonaws.com/strategy-game:latest
        secrets:
            - awsSecretAccessKey
            - adminPassword
        environment:
            LOG_AS_JSON: "true"
        ports:
            - "8080:8080"
        networks:
            - "proxy-public"
            - "application"

    database:
        image: arangodb:3.10.0
        environment:
            ARANGO_NO_AUTH: 1
        ports:
            - "8529:8529"
        networks:
            - "application"
        volumes:
            - arangodb_data_container:/var/lib/arangodb3
            - arangodb_apps_data_container:/var/lib/arangodb3-apps

volumes:
    caddy_data:
    caddy_config:
    arangodb_data_container:
    arangodb_apps_data_container:

networks:
    proxy-public:
    application:

secrets:
    awsSecretAccessKey:
        external: true
    adminPassword:
        external: true