AWSTemplateFormatVersion: "2010-09-09"

Resources:

    #===================================================================================================================
    #    Docker Repository
    #===================================================================================================================

    DockerRepository:
        Type: "AWS::ECR::Repository"
        Properties:
            ImageTagMutability: "MUTABLE"
            RepositoryName: "strategy-game"


    #===================================================================================================================
    #    Common S3-Buckets
    #===================================================================================================================

    ConfigBucket:
        Type: "AWS::S3::Bucket"
        DeletionPolicy: "Delete"
        Properties:
            BucketName: "strategy-game.config"

    GeneralLogBucket:
        Type: "AWS::S3::Bucket"
        DeletionPolicy: "Delete"
        Properties:
            BucketName: "strategy-game.logs"
            LifecycleConfiguration:
                Rules:
                    -   ExpirationInDays: 7
                        Status: Enabled

    BuildLogBucket:
        Type: "AWS::S3::Bucket"
        DeletionPolicy: "Delete"
        Properties:
            BucketName: "strategy-game.logs.build"
            LifecycleConfiguration:
                Rules:
                    -   ExpirationInDays: 7
                        Status: Enabled

    BackendArtifactBucket:
        Type: "AWS::S3::Bucket"
        DeletionPolicy: "Delete"
        Properties:
            BucketName: "strategy-game.artifacts.backend"
            LifecycleConfiguration:
                Rules:
                    -   ExpirationInDays: 7
                        Status: Enabled

    FrontendArtifactBucket:
        Type: "AWS::S3::Bucket"
        DeletionPolicy: "Delete"
        Properties:
            BucketName: "strategy-game.artifacts.frontend"
            LifecycleConfiguration:
                Rules:
                    -   ExpirationInDays: 7
                        Status: Enabled

Outputs:
    GeneralLogBucketName:
        Description: "Name of the s3-bucket holding general system logs"
        Value: !Ref GeneralLogBucket
    BuildLogBucketName:
        Description: "Name of the s3-bucket holding build logs"
        Value: !Ref BuildLogBucket
    BackendArtifactBucketName:
        Description: "Name of the s3-bucket holding the backend build artifacts"
        Value: !Ref BackendArtifactBucket
    FrontendArtifactBucketName:
        Description: "Name of the s3-bucket holding the frontend build artifacts"
        Value: !Ref FrontendArtifactBucket