AWSTemplateFormatVersion: "2010-09-09"

Resources:

    #===================================================================================================================
    #    Docker Repository
    #===================================================================================================================

    DockerRepository:
        Type: "AWS::ECR::Repository"
        Properties:
            ImageTagMutability: "MUTABLE"
            RepositoryName: "strategy-game"
