apiVersion: v1
kind: Service
metadata:
    name: database
    namespace: strategy-game
    labels:
        name: database
spec:
    selector:
        name: database
    ports:
        -   name: "8529"
            port: 8529
            targetPort: 8529
