version: 0.2

phases:
    install:
        runtime-versions:
            java: corretto11
    build:
        commands:
            - yum install tree -y
            - cd strategy-game-backend
            - aws s3 cp s3://strategy-game.config/backend/application.prod.local.conf src/main/resources/application.prod.local.conf
            - tree -a -L 5
            - chmod +x gradlew
            - ./gradlew shadowJar
    post_build:
        commands:
            - echo Build completed

artifacts:
    files:
        - strategy-game-backend/build/libs/strategy-game-backend.jar
        - infrastructure/backend/server_scripts/*.sh
        - infrastructure/backend/appspec.yml
    discard-paths: yes
