version: "3.9"

services:

    reverse_proxy:
        image: "caddy:2.6.4"
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        networks:
            - "proxy-public"
        volumes:
            - "./caddy/Caddyfile:/etc/caddy/Caddyfile"
            - "caddy_data:/data"
            - "caddy_config:/config"
        deploy:
            placement:
                constraints:
                    - node.role == manager

    app:
        image: 627717213620.dkr.ecr.eu-central-1.amazonaws.com/strategy-game:latest
        secrets:
            - secretAccessKey
            - adminPassword
        environment:
            LOG_AS_JSON: "true"
        ports:
            - "8080:8080"
        networks:
            - "proxy-public"
            - "application"

    database:
        image: arangodb:3.10.0
        environment:
            ARANGO_NO_AUTH: 1
        ports:
            - "8529:8529"
        networks:
            - "application"
        volumes:
            - arangodb_data_container:/var/lib/arangodb3
            - arangodb_apps_data_container:/var/lib/arangodb3-apps

    prometheus:
        image: prom/prometheus:v2.39.1
        ports:
            - "9090:9090"
        networks:
            - "proxy-public"
            - "application"
        volumes:
            - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
            - "prometheus_data:/prometheus"
        command: --config.file=/etc/prometheus/prometheus.yml


    grafana:
        image: grafana/grafana:9.2.1
        ports:
            - "3000:3000"
        user: "104"
        volumes:
            - "./grafana/dashboards:/etc/grafana/provisioning/dashboards"
            - "./grafana/datasources:/etc/grafana/provisioning/datasources"
            - "grafana_data:/var/lib/grafana"
        networks:
            - "proxy-public"
            - "application"

volumes:
    caddy_data:
    caddy_config:
    arangodb_data_container:
    arangodb_apps_data_container:
    prometheus_data:
    grafana_data:

networks:
    proxy-public:
    application:

secrets:
    secretAccessKey:
        external: true
    adminPassword:
        external: true