version: 0.2

phases:
    install:
        runtime-versions:
            java: corretto11
    build:
        commands:
            - cd strategy-game
            - chmod +x gradlew
            - gradlew shadowJar
    post_build:
        commands:
            - echo Build completed

artifacts:
    files:
        - strategy-game-backend/build/libs/strategy-game-backend.jar
    discard-paths: yes
