@startuml
hide circle
entity "game" {
   *id: TEXT <<PK>>
   *seed: INT
   *turn: INT
}

entity "player" {
   *id: TEXT <<PK>>
   *userId: TEXT
   *gameId: TEXT <<FK>>
   *connectionId: INT
   *state: TEXT
}

entity "player_order" {
   *id: TEXT <<PK>>
   *playerId: TEXT <<FK>>
   *turn: INT
   *data: TEXT
}

entity "tile" {
   *id: TEXT <<PK>>
   *gameId: TEXT <<FK>>
   *q: INT
   *r: INT
   *type: TEXT
}

entity "marker" {
   *id: TEXT <<PK>>
   *tileId: TEXT <<FK>>
   *playerId: TEXT <<FK>>
}

entity "country" {
   *playerId: TEXT <<PK,FK>>
   *amountMoney: FLOAT
}

player --> game
player_order --> player
tile --> game
marker --> tile
marker --> player
country --> player
@enduml


Process finished with exit code 0
