name: Deploy Backend

on: workflow_dispatch

permissions:
    id-token: write
    contents: read

jobs:
    build:

        runs-on: ubuntu-latest
        if: github.repository == 'SMILEY4/strategy-game'

        steps:

            -   name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
                    aws-region: ${{ vars.AWS_REGION }}
                    role-session-name: gh-action-deploy-backend


            -   name: Login to Amazon ECR
                id: login-ecr
                uses: aws-actions/amazon-ecr-login@v2


            -   name: Checkout
                uses: actions/checkout@v3


            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3


            -   name: Build and Push to Amazon ECR
                env:
                    REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                    REPOSITORY: strategy-game
                    IMAGE_TAG: ${{ github.sha }}
                working-directory: ./backend
                run: |
                    docker buildx build --platform linux/arm64 --load -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                    docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG


            -   name: Install SSH Key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.SSH_KEY }}
                    known_hosts: ${{ secrets.KNOWN_HOSTS }}


            -   name: Copy Files
                uses: garygrossgarten/github-action-scp@release
                with:
                    local: infrastructure/dockerstack
                    remote: application
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    privateKey: ${{ secrets.SSH_KEY }}
                    rmRemote: true

            -   name: Start new Application
                env:
                    IMAGE_TAG: ${{ github.sha }}
                    SECRET_ACCESS_KEY: "testKey"
                    ADMIN_PASSWORD: "testPw"
                run: |
                    echo "docker compose -f ~/application/docker-compose.yml down || true" | ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }}
                    echo "BACKEND_VERSION=$IMAGE_TAG SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY ADMIN_PASSWORD=$ADMIN_PASSWORD docker compose -f ~/application/docker-compose.yml up -d" | ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }}