name: Publish

on: workflow_dispatch

permissions:
    contents: read

jobs:
    build:

        runs-on: ubuntu-latest
        if: github.repository == 'SMILEY4/strategy-game'

        steps:
            -   name: Install SSH key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.SSH_KEY }}
                    known_hosts: ${{ secrets.KNOWN_HOSTS }}

            -   name: SSH
                run: ssh ${{ secrets.USERNAME }}@${{ secrets.KNOWN_HOSTS }}