name: Deploy Backend Build-Image

on: workflow_dispatch

permissions:
    id-token: write
    contents: read

jobs:
    build:

        runs-on: ubuntu-latest
        if: github.repository == 'SMILEY4/strategy-game'

        steps:

            -   name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
                    aws-region: ${{ vars.AWS_REGION }}
                    role-session-name: gh-action-deploy-backend


            -   name: Login to Amazon ECR
                id: login-ecr
                uses: aws-actions/amazon-ecr-login@v2


            -   name: Checkout
                uses: actions/checkout@v3


            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3


            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3


            -   name: Build and Push to Amazon ECR
                env:
                    REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                    REPOSITORY: strategy-game-build
                    IMAGE_TAG: ${{ github.sha }}
                working-directory: ./backend
                run: |
                    docker buildx build -f Dockerfile-Build --platform linux/arm64 --load --progress=plain --network=host -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                    docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG