// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "login": {
    "error": {
      "INTERNAL_ERROR": "general error response: unexpected server side error",
      "UNAUTHORIZED": "general error response: provided username or password is incorrect",
      "unknown": "general error response: unexpected error"
    },
    "header": {
      "subtitle": "A subtitle for the login form",
      "title": "The title of the login form"
    },
    "infoRegister": {
      "action": "Link to the register page.",
      "question": "Question whether the user does not have an account and wants to register instead."
    },
    "password": {
      "error": {
        "empty": "password validation error: is empty",
        "wrongCredentials": "validation error: username or password is incorrect"
      },
      "placeholder": "The placeholder text in the empty password input"
    },
    "rememberMe": "The label for the remember-me checkbox",
    "submit": "The form submit button text",
    "username": {
      "error": {
        "empty": "username validation error: is empty",
        "wrongCredentials": "validation error: username or password is incorrect"
      },
      "placeholder": "The placeholder text in the empty username input"
    }
  },
  "register": {
    "error": {
      "INTERNAL_ERROR": "general error response: unexpected server side error",
      "INVALID_PASSWORD": "general error response: provided password is invalid",
      "INVALID_REGISTRATION_CODE": "general error response: registration code is invalid or missing",
      "INVALID_USERNAME": "general error response: provided username is invalid",
      "USERNAME_TAKEN": "general error response: username is already taken",
      "unknown": "general error response: unexpected error"
    },
    "header": {
      "subtitle": "A subtitle for the registration form",
      "title": "The title of the registration form"
    },
    "infoLogIn": {
      "action": "Link to the log-in page.",
      "question": "Question whether the user already has an account and wants to log-in instead."
    },
    "password": {
      "error": {
        "INVALID_PASSWORD": "password validation error: is invalid",
        "empty": "password validation error: is empty"
      },
      "placeholder": "The placeholder text in the empty password input"
    },
    "passwordConfirmation": {
      "error": {
        "empty": "password confirmation error: is empty",
        "mismatch": "password confirmation error: does not match password"
      },
      "placeholder": "The placeholder text in the empty password confirmation input"
    },
    "submit": "The form submit button text",
    "username": {
      "error": {
        "INVALID_USERNAME": "username validation error: is invalid",
        "USERNAME_TAKEN": "username validation error: is already taken",
        "empty": "username validation error: is empty"
      },
      "placeholder": "The placeholder text in the empty username input"
    }
  }
}
